let opcodes = {
    "0x00": {instruction: 'brk'},
    "0x01": {instruction: 'ora', mode: 'indirectX'},
    "0x05": {instruction: 'ora', mode: 'zeroPage'},
    "0x06": {instruction: 'asl', mode: 'zeroPage'},
    "0x08": {instruction: 'php'},
    "0x09": {instruction: 'ora', mode: 'immediate'},
    "0x0a": {instruction: 'asl'},
    "0x0d": {instruction: 'ora', mode: 'absolute'},
    "0x0e": {instruction: 'asl', mode: 'absolute'},
    "0x10": {instruction: 'bpl', mode: 'relative'},
    "0x11": {instruction: 'ora', mode: 'indirectY'},
    "0x15": {instruction: 'ora', mode: 'zeroPageX'},
    "0x16": {instruction: 'asl', mode: 'zeroPageX'},
    "0x18": {instruction: 'clc'},
    "0x19": {instruction: 'ora', mode: 'absoluteY'},
    "0x1d": {instruction: 'ora', mode: 'absoluteX'},
    "0x1e": {instruction: 'asl', mode: 'absoluteX'},
    "0x20": {instruction: 'jsr', mode: 'absolute'},
    "0x21": {instruction: 'and', mode: 'indirectX'},
    "0x24": {instruction: 'bit', mode: 'zeroPage'},
    "0x25": {instruction: 'and', mode: 'zeroPage'},
    "0x26": {instruction: 'rol', mode: 'zeroPage'},
    "0x28": {instruction: 'plp'},
    "0x29": {instruction: 'and', mode: 'immediate'},
    "0x2a": {instruction: 'rol'},
    "0x2c": {instruction: 'bit', mode: 'absolute'},
    "0x2d": {instruction: 'and', mode: 'absolute'},
    "0x2e": {instruction: 'rol', mode: 'absolute'},
    "0x30": {instruction: 'bmi', mode: 'relative'},
    "0x31": {instruction: 'and', mode: 'indirectY'},
    "0x35": {instruction: 'and', mode: 'zeroPageX'},
    "0x36": {instruction: 'rol', mode: 'zeroPageX'},
    "0x38": {instruction: 'sec'},
    "0x39": {instruction: 'and', mode: 'absoluteY'},
    "0x3d": {instruction: 'and', mode: 'absoluteX'},
    "0x3e": {instruction: 'rol', mode: 'absoluteX'},
    "0x40": {instruction: 'rti'},
    "0x41": {instruction: 'eor', mode: 'indirectX'},
    "0x45": {instruction: 'eor', mode: 'zeroPage'},
    "0x46": {instruction: 'lsr', mode: 'zeroPage'},
    "0x48": {instruction: 'pha'},
    "0x49": {instruction: 'eor', mode: 'immediate'},
    "0x4a": {instruction: 'lsr'},
    "0x4c": {instruction: 'jmp', mode: 'absolute'},
    "0x4d": {instruction: 'eor', mode: 'absolute'},
    "0x4e": {instruction: 'lsr', mode: 'absolute'},
    "0x50": {instruction: 'bvc', mode: 'relative'},
    "0x51": {instruction: 'eor', mode: 'indirectY'},
    "0x55": {instruction: 'eor', mode: 'zeroPageX'},
    "0x56": {instruction: 'lsr', mode: 'zeroPageX'},
    "0x58": {instruction: 'cli'},
    "0x59": {instruction: 'eor', mode: 'absoluteY'},
    "0x5d": {instruction: 'eor', mode: 'absoluteX'},
    "0x5e": {instruction: 'lsr', mode: 'absoluteX'},
    "0x60": {instruction: 'rts'},
    "0x61": {instruction: 'adc', mode: 'indirectX'},
    "0x65": {instruction: 'adc', mode: 'zeroPage'},
    "0x66": {instruction: 'ror', mode: 'zeroPage'},
    "0x68": {instruction: 'pla'},
    "0x69": {instruction: 'adc', mode: 'immediate'},
    "0x6a": {instruction: 'ror'},
    "0x6c": {instruction: 'jmp', mode: 'indirect'},
    "0x6d": {instruction: 'adc', mode: 'absolute'},
    "0x6e": {instruction: 'ror', mode: 'absolute'},
    "0x70": {instruction: 'bvs', mode: 'relative'},
    "0x71": {instruction: 'adc', mode: 'indirectY'},
    "0x75": {instruction: 'adc', mode: 'zeroPageX'},
    "0x76": {instruction: 'ror', mode: 'zeroPageX'},
    "0x78": {instruction: 'sei'},
    "0x79": {instruction: 'adc', mode: 'absoluteY'},
    "0x7d": {instruction: 'adc', mode: 'absoluteX'},
    "0x7e": {instruction: 'ror', mode: 'absoluteX'},
    "0x81": {instruction: 'sta', mode: 'indirectX'},
    "0x84": {instruction: 'sty', mode: 'zeroPage'},
    "0x85": {instruction: 'sta', mode: 'zeroPage'},
    "0x86": {instruction: 'stx', mode: 'zeroPage'},
    "0x88": {instruction: 'dey'},
    "0x8a": {instruction: 'txa'},
    "0x8c": {instruction: 'sty', mode: 'absolute'},
    "0x8d": {instruction: 'sta', mode: 'absolute'},
    "0x8e": {instruction: 'stx', mode: 'absolute'},
    "0x90": {instruction: 'bcc', mode: 'relative'},
    "0x91": {instruction: 'sta', mode: 'indirectY'},
    "0x94": {instruction: 'sty', mode: 'zeroPageX'},
    "0x95": {instruction: 'sta', mode: 'zeroPageX'},
    "0x96": {instruction: 'stx', mode: 'zeroPageY'},
    "0x98": {instruction: 'tya'},
    "0x99": {instruction: 'sta', mode: 'absoluteY'},
    "0x9a": {instruction: 'txs'},
    "0x9d": {instruction: 'sta', mode: 'absoluteX'},
    "0xa0": {instruction: 'ldy', mode: 'immediate'},
    "0xa1": {instruction: 'lda', mode: 'indirectX'},
    "0xa2": {instruction: 'ldx', mode: 'immediate'},
    "0xa4": {instruction: 'ldy', mode: 'zeroPage'},
    "0xa5": {instruction: 'lda', mode: 'zeroPage'},
    "0xa6": {instruction: 'ldx', mode: 'zeroPage'},
    "0xa8": {instruction: 'tay'},
    "0xa9": {instruction: 'lda', mode: 'immediate'},
    "0xaa": {instruction: 'tax'},
    "0xac": {instruction: 'ldy', mode: 'absolute'},
    "0xad": {instruction: 'lda', mode: 'absolute'},
    "0xae": {instruction: 'ldx', mode: 'absolute'},
    "0xb0": {instruction: 'bcs', mode: 'relative'},
    "0xb1": {instruction: 'lda', mode: 'indirectY'},
    "0xb4": {instruction: 'ldy', mode: 'zeroPageX'},
    "0xb5": {instruction: 'lda', mode: 'zeroPageX'},
    "0xb6": {instruction: 'ldx', mode: 'zeroPageY'},
    "0xb8": {instruction: 'clv'},
    "0xb9": {instruction: 'lda', mode: 'absoluteY'},
    "0xba": {instruction: 'tsx'},
    "0xbc": {instruction: 'ldy', mode: 'absoluteX'},
    "0xbd": {instruction: 'lda', mode: 'absoluteX'},
    "0xbe": {instruction: 'ldx', mode: 'absoluteY'},
    "0xc0": {instruction: 'cpy', mode: 'immediate'},
    "0xc1": {instruction: 'cmp', mode: 'indirectX'},
    "0xc4": {instruction: 'cpy', mode: 'zeroPage'},
    "0xc5": {instruction: 'cmp', mode: 'zeroPage'},
    "0xc6": {instruction: 'dec', mode: 'zeroPage'},
    "0xc8": {instruction: 'iny'},
    "0xc9": {instruction: 'cmp', mode: 'immediate'},
    "0xca": {instruction: 'dex'},
    "0xcc": {instruction: 'cpy', mode: 'absolute'},
    "0xcd": {instruction: 'cmp', mode: 'absolute'},
    "0xce": {instruction: 'dec', mode: 'absolute'},
    "0xd0": {instruction: 'bne', mode: 'relative'},
    "0xd1": {instruction: 'cmp', mode: 'indirectY'},
    "0xd5": {instruction: 'cmp', mode: 'zeroPageX'},
    "0xd6": {instruction: 'dec', mode: 'zeroPageX'},
    "0xd8": {instruction: 'cld'},
    "0xd9": {instruction: 'cmp', mode: 'absoluteY'},
    "0xdd": {instruction: 'cmp', mode: 'absoluteX'},
    "0xde": {instruction: 'dec', mode: 'absoluteX'},
    "0xe0": {instruction: 'cpx', mode: 'immediate'},
    "0xe1": {instruction: 'sbc', mode: 'indirectX'},
    "0xe4": {instruction: 'cpx', mode: 'zeroPage'},
    "0xe5": {instruction: 'sbc', mode: 'zeroPage'},
    "0xe6": {instruction: 'inc', mode: 'zeroPage'},
    "0xe8": {instruction: 'inx'},
    "0xe9": {instruction: 'sbc', mode: 'immediate'},
    "0xea": {instruction: 'nop'},
    "0xec": {instruction: 'cpx', mode: 'absolute'},
    "0xed": {instruction: 'sbc', mode: 'absolute'},
    "0xee": {instruction: 'inc', mode: 'absolute'},
    "0xf0": {instruction: 'beq', mode: 'relative'},
    "0xf1": {instruction: 'sbc', mode: 'indirectY'},
    "0xf5": {instruction: 'sbc', mode: 'zeroPageX'},
    "0xf6": {instruction: 'inc', mode: 'zeroPageX'},
    "0xf8": {instruction: 'sed'},
    "0xf9": {instruction: 'sbc', mode: 'absoluteY'},
    "0xfd": {instruction: 'sbc', mode: 'absoluteX'},
    "0xfe": {instruction: 'inc', mode: 'absoluteX'},
}

module.exports = opcodes;